// <auto-generated />
using System;
using DataManager.Application.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataManager.Application.Core.Data.Migrations
{
    [DbContext(typeof(DataManagerDbContext))]
    [Migration("20251207174054_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DataManager.Application.Core.Modules.Log.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogType");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainHost")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("ProjectInstances");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.TranslationSets.TranslationSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedIdentityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableCultures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranslationSets", (string)null);
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.TranslationSets.TranslationSetInclude", b =>
                {
                    b.Property<Guid>("ParentTranslationSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncludedTranslationSetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentTranslationSetId", "IncludedTranslationSetId");

                    b.HasIndex("IncludedTranslationSetId");

                    b.HasIndex("ParentTranslationSetId", "IncludedTranslationSetId")
                        .IsUnique();

                    b.ToTable("TranslationSetsIncludes", (string)null);
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.Translations.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTemplate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureName")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalGroupName1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalGroupName2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDraftVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOldVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LayoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalTranslationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceTranslationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceTranslationLastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TranslationSetId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CultureName");

                    b.HasIndex("LayoutId");

                    b.HasIndex("OriginalTranslationId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceTranslationId");

                    b.HasIndex("TranslationKey");

                    b.HasIndex("TranslationSetId");

                    b.HasIndex("IsCurrentVersion", "IsDraftVersion", "IsOldVersion");

                    b.HasIndex("InternalGroupName1", "InternalGroupName2", "ResourceName", "CultureName");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.HasOne("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", "ParentProject")
                        .WithMany("ChildProjects")
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.TranslationSets.TranslationSetInclude", b =>
                {
                    b.HasOne("DataManager.Application.Core.Modules.TranslationSets.TranslationSet", "IncludedTranslationSet")
                        .WithMany("IncludedIn")
                        .HasForeignKey("IncludedTranslationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManager.Application.Core.Modules.TranslationSets.TranslationSet", "ParentTranslationSet")
                        .WithMany("Includes")
                        .HasForeignKey("ParentTranslationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncludedTranslationSet");

                    b.Navigation("ParentTranslationSet");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.Translations.Translation", b =>
                {
                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "OriginalTranslation")
                        .WithMany()
                        .HasForeignKey("OriginalTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "SourceTranslation")
                        .WithMany()
                        .HasForeignKey("SourceTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.TranslationSets.TranslationSet", "TranslationSet")
                        .WithMany()
                        .HasForeignKey("TranslationSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Layout");

                    b.Navigation("OriginalTranslation");

                    b.Navigation("Source");

                    b.Navigation("SourceTranslation");

                    b.Navigation("TranslationSet");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.Navigation("ChildProjects");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.TranslationSets.TranslationSet", b =>
                {
                    b.Navigation("IncludedIn");

                    b.Navigation("Includes");
                });
#pragma warning restore 612, 618
        }
    }
}
