// <auto-generated />
using System;
using DataManager.Application.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataManager.Application.Core.Data.Migrations
{
    [DbContext(typeof(DataManagerDbContext))]
    [Migration("20251204230333_AddSourceDataSetToTranslation")]
    partial class AddSourceDataSetToTranslation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DataManager.Application.Core.Modules.DataSet.DataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedIdentityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableCultures")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.DataSet.DataSetInclude", b =>
                {
                    b.Property<Guid>("ParentDataSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncludedDataSetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentDataSetId", "IncludedDataSetId");

                    b.HasIndex("IncludedDataSetId");

                    b.HasIndex("ParentDataSetId", "IncludedDataSetId")
                        .IsUnique();

                    b.ToTable("DataSetInclude");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainHost")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("ProjectInstances");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.Translations.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTemplate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureName")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DataSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalGroupName1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalGroupName2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDraftVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOldVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LayoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalTranslationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceDataSetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceDataSetLastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CultureName");

                    b.HasIndex("DataSetId");

                    b.HasIndex("LayoutId");

                    b.HasIndex("OriginalTranslationId");

                    b.HasIndex("SourceDataSetId");

                    b.HasIndex("SourceId");

                    b.HasIndex("IsCurrentVersion", "IsDraftVersion", "IsOldVersion");

                    b.HasIndex("InternalGroupName1", "InternalGroupName2", "ResourceName", "CultureName");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.DataSet.DataSetInclude", b =>
                {
                    b.HasOne("DataManager.Application.Core.Modules.DataSet.DataSet", "IncludedDataSet")
                        .WithMany("IncludedIn")
                        .HasForeignKey("IncludedDataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataManager.Application.Core.Modules.DataSet.DataSet", "ParentDataSet")
                        .WithMany("Includes")
                        .HasForeignKey("ParentDataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncludedDataSet");

                    b.Navigation("ParentDataSet");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.HasOne("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", "ParentProject")
                        .WithMany("ChildProjects")
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.Translations.Translation", b =>
                {
                    b.HasOne("DataManager.Application.Core.Modules.DataSet.DataSet", "DataSet")
                        .WithMany()
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "OriginalTranslation")
                        .WithMany()
                        .HasForeignKey("OriginalTranslationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.DataSet.DataSet", "SourceDataSet")
                        .WithMany()
                        .HasForeignKey("SourceDataSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataManager.Application.Core.Modules.Translations.Translation", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSet");

                    b.Navigation("Layout");

                    b.Navigation("OriginalTranslation");

                    b.Navigation("Source");

                    b.Navigation("SourceDataSet");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.DataSet.DataSet", b =>
                {
                    b.Navigation("IncludedIn");

                    b.Navigation("Includes");
                });

            modelBuilder.Entity("DataManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.Navigation("ChildProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
